### ISSUE TITLE
Hackweek TODOs

### ISSUE THREAD

**Issue by lforst** [getsentry/hackweek-sentry-unplugin#20]
## Stage 0 - Prelude

- [x] Uplugin explanation session
- [x] Repo explanation session

## Stage 1 - MVP

- [x] Finish up / rethink release injection mechanism (https://github.com/getsentry/hackweek-sentry-unplugin/pull/24)
- [x] Write function to get a proper `release` value (https://github.com/getsentry/hackweek-sentry-unplugin/pull/21, https://github.com/getsentry/hackweek-sentry-unplugin/pull/22)
- [x] Source maps upload 1.0  (https://github.com/getsentry/hackweek-sentry-unplugin/pull/23)
  - [x] Do what Sentry CLI does while uploading source maps (in MVP form).  (https://github.com/getsentry/hackweek-sentry-unplugin/pull/26)
- [x] Source maps Upload 2.0
  - [x] Replace Sentry-CLI calls step by step:
    - [x]  (required) create release (https://github.com/getsentry/hackweek-sentry-unplugin/pull/29)
    - [x] (required) cleanArtifcats (https://github.com/getsentry/hackweek-sentry-unplugin/pull/30)
    - [x] (required) upload sourcemaps (https://github.com/getsentry/hackweek-sentry-unplugin/pull/33)
    - [x] (required) finalize release (https://github.com/getsentry/hackweek-sentry-unplugin/pull/32)
- [x] Handle `entries` option (https://github.com/getsentry/hackweek-sentry-unplugin/pull/38, ref: https://github.com/getsentry/hackweek-sentry-unplugin/issues/28)
- [x] Remove facade (#46)

## Stage 2 - Ship

- [x] Get license figured out (https://github.com/getsentry/hackweek-sentry-unplugin/issues/5)
- [x] Check package jsons (implicitly done in https://github.com/getsentry/hackweek-sentry-unplugin/pull/42)
- [x] Write READMEs (#39)
- [ ] Add examples to readmes
- [ ] Add CHANGELOG
- [ ] Remove any console logs that are not explicit debug logging
- [ ] Publish package

## Stage 3 - Feature parity with webpack plugin
- [ ] Extend basic functionality with all options from webpack plugin
- [ ] add missing commands for release creation pipeline:
    - [ ] set commits  
    - [ ] add deploy
- [ ] To be defined

## Misc Todos:

- [x] Write integration tests (https://github.com/getsentry/hackweek-sentry-unplugin/pull/25)
- [x] Try out Nx (https://github.com/getsentry/hackweek-sentry-unplugin/pull/37)
- [x] Add Sentry (https://github.com/getsentry/hackweek-sentry-unplugin/pull/36)

**Comment by lforst** [comment]
Hackweek is over. Good job everybody. Now we go for the release!
